### ISSUE TITLE
PSRAM Error on Startup

### ISSUE THREAD

**Issue by SMEAC** [OzInFl/Elecrow3_5_RGB_TFT_SQARELINE#1]
After reset, chip throws PSRAM Error, and Loop() doesn't continue.  TFT Screen continues to get updated, timers are working.
Error seen in Monitor Terminal:

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0xb (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
E (219) psram: PSRAM ID read error: 0x00ffffff
```

**Comment by OzInFl** [comment]
Ill get it hooked back up and see what I get, stby for update...

**Comment by OzInFl** [comment]
I did the same and noticed that the loop doesent execute as you would expect! as for why, I havent figured it out yet! Very Strange! Ill mess with it again this weekend and see if I cant figure out why its not firing the loop statements.

**Comment by SMEAC** [comment]
Have a few updates here.
The loop is actually working, but due to the 
` -DARDUINO_USB_CDC_ON_BOOT`
in the platformio, there is no usb in debug terminal.
Removing that and it appears the loop is working.

I also think I have a fix for the PSRAM issue.  Can you test the following changes to the Platformio File:

`[env:esp32-s3-devkitc-1]
platform = espressif32

board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
	-DESP32S3
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-D LV_CONF_INCLUDE_SIMPLE
	-I./include
	-I./src/squareline
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB`

**Comment by OzInFl** [comment]
Thats fantastic! I had done some research and saw someone else having a similar issue but they did state that the loop was still running, but not getting serial output threw me off! I also tested some code to update one of the LVGL widgets and that was not working either. Never thought about the CDC boot option, makes sense. Dont really need it in this case but might be good for access to spiffs via USBC??  Havent spent any time on that other than seeing it in espressifs docs. Thanks for figuring out whats up!!

**Comment by OzInFl** [comment]
Changes Committed - Credits Given to [SMEAC](https://github.com/SMEAC) for the corrected board type that fixed the loop not running! Thanks again!
